In [1]:
import pandas as pd

akas = '/Users/algaumon/Downloads/Projet_2/VS_code_akas/akas_fr_en_filtered.tsv'
movies = '/Users/algaumon/Documents/Projet_2/VS_code_akas/movies.tsv'
df_akas = pd.read_csv(akas, sep='\t')
df_movies = pd.read_csv(movies, sep='\t')

/var/folders/w1/qtwp73x57d39n1yby0x4vj800000gn/T/ipykernel_23146/821354911.py:6: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_movies = pd.read_csv(movies, sep='\t')

In [2]:
df_akas[df_akas['title']=='The Grudge']

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
171353,tt0370848,2,The Grudge,XWW,en,\N,\N,0
176855,tt0391198,12,The Grudge,PH,en,imdbDisplay,\N,0
176856,tt0391198,14,The Grudge,SG,en,imdbDisplay,\N,0
176857,tt0391198,15,The Grudge,TH,en,imdbDisplay,\N,0
176858,tt0391198,17,The Grudge,ZA,en,imdbDisplay,\N,0
176859,tt0391198,3,The Grudge,CA,en,imdbDisplay,\N,0
176861,tt0391198,5,The Grudge,EG,en,imdbDisplay,\N,0
176862,tt0391198,8,The Grudge,ID,en,imdbDisplay,\N,0
176863,tt0391198,9,The Grudge,IN,en,imdbDisplay,\N,0
4073369,tt3612126,10,The Grudge,ID,en,imdbDisplay,\N,0
4073370,tt3612126,11,The Grudge,IN,en,imdbDisplay,\N,0
4073371,tt3612126,15,The Grudge,NZ,en,imdbDisplay,\N,0
4073372,tt3612126,16,The Grudge,PH,en,imdbDisplay,\N,0
4073373,tt3612126,18,The Grudge,SG,en,imdbDisplay,\N,0
4073374,tt3612126,19,The Grudge,TH,en,imdbDisplay,\N,0
4073375,tt3612126,21,The Grudge,ZA,en,imdbDisplay,\N,0
4073378,tt3612126,5,The Grudge,CA,en,imdbDisplay,\N,0
4073379,tt3612126,7,The Grudge,EG,en,imdbDisplay,\N,0

In [3]:
df_movies[df_movies['primaryTitle']=='The Grudge']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
184860,tt0370848,movie,The Grudge,Kineh,0,1954,\N,100,"Adventure,Drama"
191169,tt0391198,movie,The Grudge,The Grudge,0,2004,\N,91,"Horror,Mystery,Thriller"
236270,tt10443830,movie,The Grudge,The Grudge,0,2017,\N,\N,\N
350812,tt15790824,movie,The Grudge,The Grudge,0,2016,\N,\N,Drama
359578,tt16425368,movie,The Grudge,The Grudge,0,2020,\N,\N,Drama
549647,tt3612126,movie,The Grudge,The Grudge,0,2019,\N,94,"Fantasy,Horror"

In [4]:
df_combined = pd.merge(df_movies, df_akas, left_on='tconst', right_on='titleId', how='inner')

In [5]:
df_combined[df_combined['title'].apply(lambda x: 'Gendarme' in x)]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
15757,tt0043606,movie,Cops and Robbers,Guardie e ladri,0,1951,\N,105,"Comedy,Drama",tt0043606,11,Gendarmes et voleurs,BE,fr,\N,\N,0
29056,tt0058135,movie,The Gendarme of Saint-Tropez,Le gendarme de Saint-Tropez,0,1964,\N,90,"Comedy,Crime",tt0058135,3,The Gendarme of Saint-Tropez,CA,en,imdbDisplay,\N,0
29058,tt0058135,movie,The Gendarme of Saint-Tropez,Le gendarme de Saint-Tropez,0,1964,\N,90,"Comedy,Crime",tt0058135,37,Le Gendarme De Saint-Tropez,EG,en,imdbDisplay,\N,0
29059,tt0058135,movie,The Gendarme of Saint-Tropez,Le gendarme de Saint-Tropez,0,1964,\N,90,"Comedy,Crime",tt0058135,4,The Gendarme of Saint-Tropez,NZ,en,imdbDisplay,\N,0
29060,tt0058135,movie,The Gendarme of Saint-Tropez,Le gendarme de Saint-Tropez,0,1964,\N,90,"Comedy,Crime",tt0058135,6,The Gendarme of Saint-Tropez,XWW,en,imdbDisplay,\N,0
29061,tt0058135,movie,The Gendarme of Saint-Tropez,Le gendarme de Saint-Tropez,0,1964,\N,90,"Comedy,Crime",tt0058135,7,The Gendarme of Saint-Tropez,ZA,en,imdbDisplay,\N,0
31240,tt0060450,movie,The Gendarme in New York,Le gendarme à New York,0,1965,\N,102,"Comedy,Crime",tt0060450,14,The Gendarme in New York,XWW,en,imdbDisplay,\N,0
34004,tt0063005,movie,The Gendarme Gets Married,Le gendarme se marie,0,1968,\N,92,"Comedy,Romance",tt0063005,11,The Gendarme Gets Married,XWW,en,imdbDisplay,\N,0
36579,tt0065769,movie,The Gendarme Takes Off,Le gendarme en balade,0,1970,\N,107,"Comedy,Crime",tt0065769,12,The Gendarme Takes Off,XWW,en,imdbDisplay,\N,0
36581,tt0065769,movie,The Gendarme Takes Off,Le gendarme en balade,0,1970,\N,107,"Comedy,Crime",tt0065769,42,The Gendarme on Promenade,XWW,en,\N,alternative spelling,0
49520,tt0079200,movie,The Gendarme and the Extra-Terrestrials,Le gendarme et les extra-terrestres,0,1979,\N,96,"Comedy,Crime,Sci-Fi",tt0079200,15,The Gendarme and the Extra-Terrestrials,XWW,en,imdbDisplay,\N,0
49522,tt0079200,movie,The Gendarme and the Extra-Terrestrials,Le gendarme et les extra-terrestres,0,1979,\N,96,"Comedy,Crime,Sci-Fi",tt0079200,3,The Gendarme and the Extra-terrestrials,CA,en,imdbDisplay,\N,0
49523,tt0079200,movie,The Gendarme and the Extra-Terrestrials,Le gendarme et les extra-terrestres,0,1979,\N,96,"Comedy,Crime,Sci-Fi",tt0079200,4,The Gendarme and the Extra-terrestrials,IE,en,imdbDisplay,\N,0
49525,tt0079200,movie,The Gendarme and the Extra-Terrestrials,Le gendarme et les extra-terrestres,0,1979,\N,96,"Comedy,Crime,Sci-Fi",tt0079200,5,The Gendarme and the Extra-terrestrials,NZ,en,imdbDisplay,\N,0
49526,tt0079200,movie,The Gendarme and the Extra-Terrestrials,Le gendarme et les extra-terrestres,0,1979,\N,96,"Comedy,Crime,Sci-Fi",tt0079200,6,The Gendarme and the Extra-terrestrials,ZA,en,imdbDisplay,\N,0
54056,tt0083996,movie,The Gendarme and the Gendarmettes,Le gendarme et les gendarmettes,0,1982,\N,102,"Comedy,Crime",tt0083996,16,The Gendarme and the Gendarmettes,XWW,en,imdbDisplay,\N,0
93022,tt0157691,movie,The Gendarme of Champignol,Le gendarme de Champignol,0,1959,\N,90,Comedy,tt0157691,4,The Gendarme of Champignol,XWW,en,\N,\N,0
178609,tt1111902,movie,Gholam zhandarm,Gholam zhandarm,0,1971,\N,90,"Adventure,Biography,Crime",tt1111902,2,"Gholam, the Gendarme",XWW,en,\N,literal title,0

In [6]:
df_filme = df_combined.drop(columns=['titleType','primaryTitle','titleId','ordering','types','attributes','isOriginalTitle'])

In [7]:
df_filme

,tconst,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,title,region,language
0,tt0000574,The Story of the Kelly Gang,0,1906,\N,70,"Action,Adventure,Biography",The Story of the Kelly Gang,SG,en
1,tt0000838,A Cultura do Cacau,0,1909,\N,\N,\N,The Cultivation of the Cacao Tree,XWW,en
2,tt0000941,Locura de amor,0,1909,\N,45,Drama,Love Crazy,XWW,en
3,tt0001051,El sueño milagroso,0,1909,\N,\N,\N,Magical Dream,XWW,en
4,tt0001122,L'auberge rouge,0,1910,\N,\N,\N,The Red Inn,XWW,en
...,...,...,...,...,...,...,...,...,...,...
381975,tt9916362,Akelarre,0,2020,\N,92,"Drama,History",Les sorcières d'Akelarre,CA,fr
381976,tt9916362,Akelarre,0,2020,\N,92,"Drama,History",Coven,CA,en
381977,tt9916362,Akelarre,0,2020,\N,92,"Drama,History",Coven,EG,en
381978,tt9916428,Hong xing zhao yao Zhong guo,0,2019,\N,\N,"Adventure,History,War",The Secret of China,XWW,en
381979,tt9916706,Dankyavar Danka,0,2013,\N,\N,Comedy,Dankyavar Danka,IN,en

In [8]:
df_filmindex= df_filme.reindex(['tconst','originalTitle','title','startYear','isAdult','runtimeMinutes','genres','region','language'],axis = 1)

In [9]:
df_filmindex[df_filmindex['title'].apply(lambda x: 'Gendarme' in x)]

,tconst,originalTitle,title,startYear,isAdult,runtimeMinutes,genres,region,language
15757,tt0043606,Guardie e ladri,Gendarmes et voleurs,1951,0,105,"Comedy,Drama",BE,fr
29056,tt0058135,Le gendarme de Saint-Tropez,The Gendarme of Saint-Tropez,1964,0,90,"Comedy,Crime",CA,en
29058,tt0058135,Le gendarme de Saint-Tropez,Le Gendarme De Saint-Tropez,1964,0,90,"Comedy,Crime",EG,en
29059,tt0058135,Le gendarme de Saint-Tropez,The Gendarme of Saint-Tropez,1964,0,90,"Comedy,Crime",NZ,en
29060,tt0058135,Le gendarme de Saint-Tropez,The Gendarme of Saint-Tropez,1964,0,90,"Comedy,Crime",XWW,en
29061,tt0058135,Le gendarme de Saint-Tropez,The Gendarme of Saint-Tropez,1964,0,90,"Comedy,Crime",ZA,en
31240,tt0060450,Le gendarme à New York,The Gendarme in New York,1965,0,102,"Comedy,Crime",XWW,en
34004,tt0063005,Le gendarme se marie,The Gendarme Gets Married,1968,0,92,"Comedy,Romance",XWW,en
36579,tt0065769,Le gendarme en balade,The Gendarme Takes Off,1970,0,107,"Comedy,Crime",XWW,en
36581,tt0065769,Le gendarme en balade,The Gendarme on Promenade,1970,0,107,"Comedy,Crime",XWW,en
49520,tt0079200,Le gendarme et les extra-terrestres,The Gendarme and the Extra-Terrestrials,1979,0,96,"Comedy,Crime,Sci-Fi",XWW,en
49522,tt0079200,Le gendarme et les extra-terrestres,The Gendarme and the Extra-terrestrials,1979,0,96,"Comedy,Crime,Sci-Fi",CA,en
49523,tt0079200,Le gendarme et les extra-terrestres,The Gendarme and the Extra-terrestrials,1979,0,96,"Comedy,Crime,Sci-Fi",IE,en
49525,tt0079200,Le gendarme et les extra-terrestres,The Gendarme and the Extra-terrestrials,1979,0,96,"Comedy,Crime,Sci-Fi",NZ,en
49526,tt0079200,Le gendarme et les extra-terrestres,The Gendarme and the Extra-terrestrials,1979,0,96,"Comedy,Crime,Sci-Fi",ZA,en
54056,tt0083996,Le gendarme et les gendarmettes,The Gendarme and the Gendarmettes,1982,0,102,"Comedy,Crime",XWW,en
93022,tt0157691,Le gendarme de Champignol,The Gendarme of Champignol,1959,0,90,Comedy,XWW,en
178609,tt1111902,Gholam zhandarm,"Gholam, the Gendarme",1971,0,90,"Adventure,Biography,Crime",XWW,en

In [10]:
df_sorted = df_filmindex.sort_values(by='region', ascending=False)
df_ok = df_sorted.drop_duplicates(subset='tconst', keep='first')

In [11]:
df_ok[df_ok['originalTitle'].apply(lambda x: 'gendarme' in x)]

,tconst,originalTitle,title,startYear,isAdult,runtimeMinutes,genres,region,language
29061,tt0058135,Le gendarme de Saint-Tropez,The Gendarme of Saint-Tropez,1964,0,90,"Comedy,Crime",ZA,en
49526,tt0079200,Le gendarme et les extra-terrestres,The Gendarme and the Extra-terrestrials,1979,0,96,"Comedy,Crime,Sci-Fi",ZA,en
93022,tt0157691,Le gendarme de Champignol,The Gendarme of Champignol,1959,0,90,Comedy,XWW,en
93818,tt0161609,El gendarme desconocido,The Unknown Policeman,1941,0,108,"Comedy,Crime,Drama",XWW,en
34005,tt0063005,Le gendarme se marie,The Troops get Married,1968,0,92,"Comedy,Romance",XWW,en
36582,tt0065769,Le gendarme en balade,The Troops on Vacation,1970,0,107,"Comedy,Crime",XWW,en
31244,tt0060450,Le gendarme à New York,The Troops in New York,1965,0,102,"Comedy,Crime",XWW,en
54056,tt0083996,Le gendarme et les gendarmettes,The Gendarme and the Gendarmettes,1982,0,102,"Comedy,Crime",XWW,en

In [12]:
df_ok['startYear'] = pd.to_numeric(df_ok['startYear'], errors='coerce')

/var/folders/w1/qtwp73x57d39n1yby0x4vj800000gn/T/ipykernel_23146/406086524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ok['startYear'] = pd.to_numeric(df_ok['startYear'], errors='coerce')

In [13]:
df_ok['startYear'].fillna(0, inplace=True)  # Exemple avec 0

/var/folders/w1/qtwp73x57d39n1yby0x4vj800000gn/T/ipykernel_23146/2012624644.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ok['startYear'].fillna(0, inplace=True)  # Exemple avec 0
/var/folders/w1/qtwp73x57d39n1yby0x4vj800000gn/T/ipykernel_23146/2012624644.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ok['startYear'].fillna(0, inplace=True)  # Exemple avec 0

In [14]:
df_ok['startYear'] = df_ok['startYear'].astype(int)

/var/folders/w1/qtwp73x57d39n1yby0x4vj800000gn/T/ipykernel_23146/2399826332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ok['startYear'] = df_ok['startYear'].astype(int)

In [15]:
df_ok=df_ok[df_ok['startYear']!=0]

In [16]:
df_ok.sort_values('startYear', ascending=False)

,tconst,originalTitle,title,startYear,isAdult,runtimeMinutes,genres,region,language
337329,tt5637536,Avatar 5,Avatar 5,2031,0,\N,"Action,Adventure,Fantasy",IN,en
300480,tt3095356,Avatar 4,Avatar 4,2029,0,\N,"Action,Adventure,Fantasy",IN,en
299302,tt30497626,Animal Park,Animal Park,2027,0,\N,"Action,Crime,Drama",CA,en
307037,tt32890033,Minions 3,Mega Minions,2027,0,\N,"Action,Adventure,Animation",CA,en
261714,tt21361444,Avengers: Secret Wars,Avengers: Secret Wars,2027,0,\N,"Action,Adventure,Sci-Fi",IN,en
...,...,...,...,...,...,...,...,...,...
119043,tt0272707,Le Longchamp fleuri,Longchamp in Bloom,1905,0,\N,Documentary,BE,en
119035,tt0272654,De heilige bloedprocessie,The Procession of the Holy Blood,1905,0,\N,Documentary,BE,en
146420,tt0420843,Prinsesse Marie til hest,Princess Marie on Horseback,1903,0,\N,Documentary,XEU,en
87504,tt0127962,La vie et la passion de Jésus Christ,The Life and Passion of Christ,1903,0,45,"Biography,Drama",XWW,en
119023,tt0272561,Le cortège du pèlerinage des combattants de 18...,Pilgrimage Cortege of the 1830 Veterans of Ste...,1902,0,\N,Documentary,XWW,en

In [17]:
condition_start = df_ok['startYear'] > 1936
df_cond = df_ok[condition_start]

In [18]:
condition_end = df_cond['startYear'] < 2025
df_top = df_cond[condition_end]

In [19]:
df_top.sort_values('startYear',ascending=False, inplace=True)

/var/folders/w1/qtwp73x57d39n1yby0x4vj800000gn/T/ipykernel_23146/374520626.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top.sort_values('startYear',ascending=False, inplace=True)

In [20]:
df_top= df_top[df_top['runtimeMinutes']!='\\N']

In [21]:
df_top = df_top[df_top['genres'] != r'\N']

In [27]:
df_top[df_top['originalTitle'].apply(lambda x: 'La vie ' in x)]

,tconst,originalTitle,title,startYear,isAdult,runtimeMinutes,genres,region,language
299209,tt30471155,Operation Portugal 2 - La vie de chateau,Operation Portugal 2: Castle Life,2024,0,93,Comedy,XWW,en
282860,tt26660615,La vie pour de vrai,Life for Real,2023,0,110,Comedy,XWW,en
279315,tt25386452,La vie de ma mère,This Is My Mother,2023,0,105,"Comedy,Drama",XWW,en
261152,tt21292166,La vie des hommes infâmes,The Lives of Infamous Men,2022,0,83,Drama,XWW,en
250961,tt19358082,La vie d'après,The Life After,2021,0,105,Drama,XWW,en
...,...,...,...,...,...,...,...,...,...
93769,tt0161065,La vie chantée,Life in a Song,1951,0,80,"Comedy,Musical,Romance",XWW,en
93770,tt0161067,La vie est un jeu,Life Is a Game,1951,0,82,Comedy,XWW,en
90054,tt0140679,La vie commence demain,La vie commence demain,1950,0,86,"Documentary,Drama",BE,fr
221261,tt1483743,Autant en emporte l'histoire - La vie privée d...,Gone with History,1949,0,75,"Documentary,History",XWW,en
89186,tt0136603,La vie en rose,A Merry Life,1948,0,96,Drama,XWW,en